mxdpgs – psqp
mxdpgs Subroutine
91/12/01
11 statements
Source File
public pure subroutine mxdpgs(n, a, alf)
scaling of a dense symmetric positive definite matrix a+e using the factorization a+e=l*d*trans(l) obtained by the subroutine mxdpgf.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
order of the matrix a.
real(kind=wp), intent(inout) :: a(*)
a(n*(n+1)/2) factorization a+e=l*d*trans(l) obtained by the subroutine mxdpgf.
real(kind=wp), intent(in) :: alf
scaling factor.
Called by
Source Code
      pure subroutine mxdpgs(n,a,alf)
      real(wp),intent(in) :: alf  !! scaling factor.
      integer,intent(in) :: n  !! order of the matrix a.
      real(wp),intent(inout) :: a(*)  !! `a(n*(n+1)/2)` factorization `a+e=l*d*trans(l)`
                                      !! obtained by the subroutine [[mxdpgf]].
      integer :: i , j
      j = 0
      do i = 1 , n
         j = j + i
         a(j) = a(j)*alf
      end do
      end subroutine mxdpgs
Call graph
bfgs_variable_metric_update calls mxdpgs
psqp calls bfgs_variable_metric_update
psqpn calls psqp