mxvcop – psqp
mxvcop Subroutine
88/12/01
9 statements
Source File
public pure subroutine mxvcop(n, x, y)
copying of a vector.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
vector dimension.
real(kind=wp), intent(in) :: x(*)
x(n) input vector.
real(kind=wp), intent(out) :: y(*)
y(n) output vector where y:= x.
Called by
Source Code
      pure subroutine mxvcop(n,x,y)
      integer,intent(in) :: n  !! vector dimension.
      real(wp),intent(in) :: x(*)  !! x(n)  input vector.
      real(wp),intent(out) :: y(*)  !! y(n)  output vector where `y:= x`.
      integer :: i
      do i = 1 , n
         y(i) = x(i)
      end do
      end subroutine mxvcop
Call graph
bfgs_variable_metric_update calls mxvcop
compute_con_and_dcon calls mxvcop
dual_range_space_quad_prog calls mxvcop, update_tri_decomp_general, ops_after_constr_deletion
psqp calls mxvcop, bfgs_variable_metric_update, compute_con_and_dcon, dual_range_space_quad_prog
update_tri_decomp_general calls mxvcop
update_tri_decomp_orthogonal calls mxvcop
ops_after_constr_deletion calls update_tri_decomp_orthogonal
psqpn calls psqp