mxvdir – psqp
mxvdir Subroutine
91/12/01
11 statements
Source File
public pure subroutine mxvdir(n, a, x, y, z)
vector augmented by the scaled vector.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
vector dimension.
real(kind=wp), intent(in) :: a
scaling factor.
real(kind=wp), intent(in) :: x(*)
x(n) input vector.
real(kind=wp), intent(in) :: y(*)
y(n) input vector.
real(kind=wp), intent(out) :: z(*)
z(n) output vector where z:= y + a*x.
Called by
Source Code
      pure subroutine mxvdir(n,a,x,y,z)
      integer,intent(in) :: n !! vector dimension.
      real(wp),intent(in) :: a !! scaling factor.
      real(wp),intent(in) :: x(*) !! x(n)  input vector.
      real(wp),intent(in) :: y(*) !! y(n)  input vector.
      real(wp),intent(out) :: z(*) !! z(n)  output vector where `z:= y + a*x`.
      integer :: i
      do i = 1 , n
         z(i) = y(i) + a*x(i)
      end do
      end subroutine mxvdir
Call graph
bfgs_variable_metric_update calls mxvdir
dual_range_space_qp calls mxvdir
dual_range_space_quad_prog calls mxvdir
psqp calls mxvdir, bfgs_variable_metric_update, dual_range_space_qp, dual_range_space_quad_prog
psqpn calls psqp