mxvdot – psqp
mxvdot Function
91/12/01
7 statements
Source File
public pure function mxvdot(n, x, y)
dot product of two vectors.
JW: rewrote this routine.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
vector dimension.
real(kind=wp), intent(in) :: x(*)
x(n) input vector.
real(kind=wp), intent(in) :: y(*)
y(n) input vector.
Return Value real(kind=wp)
value of dot product mxvdot=trans(x)*y.
Called by
Source Code
      pure function mxvdot(n,x,y)
      integer,intent(in) :: n  !!vector dimension.
      real(wp),intent(in) :: x(*)  !! x(n)  input vector.
      real(wp),intent(in) :: y(*)  !! y(n)  input vector.
      real(wp) :: mxvdot  !! value of dot product `mxvdot=trans(x)*y`.
      mxvdot = dot_product(x(1:n),y(1:n))
      end function mxvdot
Call graph
bfgs_variable_metric_update calls mxvdot
determine_new_active_linear_constr calls mxvdot
psqp calls mxvdot, bfgs_variable_metric_update, dual_range_space_quad_prog
update_tri_decomp_general calls mxvdot
dual_range_space_quad_prog calls determine_new_active_linear_constr, update_tri_decomp_general
psqpn calls psqp