mxvneg – psqp
mxvneg Subroutine
88/12/01
9 statements
Source File
public pure subroutine mxvneg(n, x, y)
change the signs of vector elements.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
vector dimension.
real(kind=wp), intent(in) :: x(*)
x(n) input vector.
real(kind=wp), intent(out) :: y(*)
y(n) output vector where y:= - x.
Called by
Source Code
      pure subroutine mxvneg(n,x,y)
      integer,intent(in) :: n  !! vector dimension.
      real(wp),intent(in) :: x(*)  !! x(n)  input vector.
      real(wp),intent(out) :: y(*)  !! y(n)  output vector where `y:= - x`.
      integer :: i
      do i = 1 , n
         y(i) = -x(i)
      end do
      end subroutine mxvneg
Call graph
compute_obj_and_dobj calls mxvneg
dual_range_space_quad_prog calls mxvneg
psqp calls compute_obj_and_dobj, dual_range_space_quad_prog
psqpn calls psqp