mxvset – psqp
mxvset Subroutine
88/12/01
9 statements
Source File
public pure subroutine mxvset(n, a, x)
a scalar is set to all the elements of a vector.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
vector dimension.
real(kind=wp), intent(in) :: a
initial value.
real(kind=wp), intent(out) :: x(*)
x(n) output vector such that x(i)=a for all i.
Called by
Source Code
      pure subroutine mxvset(n,a,x)
      real(wp),intent(in) :: a  !! initial value.
      integer,intent(in) :: n  !! vector dimension.
      real(wp),intent(out) :: x(*)  !! x(n)  output vector such that `x(i)=a` for all i.
      integer :: i
      do i = 1 , n
         x(i) = a
      end do
      end subroutine mxvset
Call graph
psqp calls mxvset, dual_range_space_quad_prog
update_tri_decomp_general calls mxvset
update_tri_decomp_orthogonal calls mxvset
dual_range_space_quad_prog calls update_tri_decomp_general, ops_after_constr_deletion
ops_after_constr_deletion calls update_tri_decomp_orthogonal
psqpn calls psqp